name: Test
on:
  pull_request: ~
  push:
    branches:
    - main

permissions: read-all

jobs:
  test:
    name: ${{ matrix.node-version }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        node-version:
        - 0.8.28
        - 0.10.31
        - 0.12.0
        - 4.0.0
        - 5.0.0
        - 6.0.0
        - 7.0.0
        - 8.0.0
        - 9.0.0
        - 10.0.0
        - 11.0.0
        - 12.0.0
        - 13.0.0
        - 14.0.0
        - 15.0.0
        - 16.0.0
        - 17.0.0
        - 18.0.0
        - 19.0.0
        - 20.0.0
        - 21.0.0
        - 22.0.0
        - 23.0.0
        - 24.0.0
        - 25.0.0
        - 26.0.0
    steps:
    - name: Checkout repository
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        persist-credentials: false
    - name: Install Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run tests
      run: node test.js
